name: Provision 2 EC2 Instances & Configure with Ansible

on:
  push:
    branches:
      - terraform-ansible

jobs:
  provision-and-configure:
    runs-on: ubuntu-latest

    # Provide AWS credentials and region via environment variables
    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # Initialize Terraform (needs AWS creds for S3 backend)
      - name: Terraform Init
        working-directory: ./infra
        run: terraform init

      # Destroy any existing EC2 instances (immutable infrastructure approach)
      - name: Terraform Destroy (destroy previous instances)
        working-directory: ./infra
        run: terraform destroy -auto-approve || echo "Nothing to destroy"

      # Create new EC2 instances
      - name: Terraform Apply (create new instances)
        working-directory: ./infra
        run: terraform apply -auto-approve

      # Save public IPs of new instances to file
      - name: Save Terraform Output to ips.json
        working-directory: ./infra
        run: terraform output -json instance_public_ips > ips.json

      # Install Ansible and jq before using them
      - name: Install Ansible and jq
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible jq

      # Remove old inventory if present
      - name: Clean old inventory if exists
        run: rm -f inventory.ini

      # Generate Ansible inventory from Terraform output
      - name: Generate Ansible Inventory
        run: |
          echo "[aws]" > inventory.ini
          index=1
          for ip in $(jq -r '.[]' ./infra/ips.json); do
            echo "aws${index} ansible_host=${ip} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-key" >> inventory.ini
            index=$((index+1))
          done
          echo "--- Inventory Generated ---"
          cat inventory.ini

      # Add the SSH private key from secrets
      - name: Inject SSH Private Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEVOPS_SSH_KEY }}" > ~/.ssh/devops-key
          chmod 600 ~/.ssh/devops-key

      # Run the Ansible playbook
      - name: Run Ansible Playbook
        env:
          ANSIBLE_HOST_KEY_CHECKING: False
        run: ansible-playbook -i inventory.ini ansible/servers-playbook.yaml --private-key ~/.ssh/devops-key -u ubuntu
