name: Provision 2 EC2 Instances & Configure with Ansible

on:
  push:
    branches:
      - terraform-ansible

jobs:
  provision-and-configure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install dependencies (Ansible, jq)
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible jq

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./infra
        run: terraform init

      - name: Terraform Apply
        working-directory: ./infra
        run: terraform apply -auto-approve

      - name: Generate Ansible Inventory from Terraform Output
        working-directory: ./infra
        run: |
          echo "[webservers]" > ../../inventory.ini
          terraform output -json instance_public_ips | jq -r '.[]' >> ../../inventory.ini

      - name: Add SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEVOPS_SSH_KEY }}" > ~/.ssh/devops-key
          chmod 600 ~/.ssh/devops-key

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory.ini ansible/playbook.yaml \
            --private-key ~/.ssh/devops-key -u ubuntu
