name: Provision EC2 Instances & Configure with Ansible

on:
  push:
    branches:
      - terraform-ansible

jobs:
  provision-and-configure:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible jq

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        working-directory: ./infra
        run: terraform init

      - name: Terraform Apply
        working-directory: ./infra
        run: terraform apply -auto-approve

      - name: Save Terraform output to clean JSON
        working-directory: ./infra
        run: |
          terraform output -json instance_public_ips > $GITHUB_WORKSPACE/ips.json
          echo "Saved instance IPs:"
          cat $GITHUB_WORKSPACE/ips.json

      - name: Generate Ansible Inventory
        run: |
          echo "[aws]" > inventory.ini
          index=1
          for ip in $(jq -r '.[]' ips.json); do
            echo "aws${index} ansible_host=${ip} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-key" >> inventory.ini
            index=$((index+1))
          done

          echo "[azure]" >> inventory.ini
          echo "azure1 ansible_host=172.190.160.163 ansible_user=azure-user ansible_ssh_private_key_file=/home/vagrant/project-ansible/node-servers/azure/azure-user.pem" >> inventory.ini
          echo "azure2 ansible_host=20.120.100.154 ansible_user=azure-user ansible_ssh_
