name: Provision 2 EC2 Instances & Configure with Ansible

on:
  push:
    branches:
      - terraform-ansible

jobs:
  provision-and-configure:
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: us-east-1
      AWS_REGION: us-east-1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: ./infra

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve
        working-directory: ./infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Get Terraform Output to ips.json
        run: terraform output -json instance_public_ips > ips.json
        working-directory: ./infra
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Clean old inventory.ini if exists
        run: |
          if [ -f inventory.ini ]; then
            rm inventory.ini
            echo "Old inventory.ini removed"
          fi

      - name: Generate dynamic inventory.ini from ips.json
        run: |
          echo "[aws]" > inventory.ini
          index=1
          for ip in $(jq -r '.[]' ./infra/ips.json); do
            echo "aws${index} ansible_host=${ip} ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/devops-key" >> inventory.ini
            index=$((index+1))
          done
          echo "--- Inventory Generated ---"
          cat inventory.ini

      - name: Run Ansible Playbook
        uses: appleboy/ansible-playbook-action@v0.4.3
        with:
          playbook: ./ansible/servers-playbook.yaml
          inventory: ./inventory.ini
          ssh-private-key: ${{ secrets.DEVOPS_SSH_KEY }}
